#!/bin/bash

echo "=== AIRDROP NVIM ==="

apt-get install sudo
sudo apt-get update && sudo apt-get upgrade -y

echo "=== INSTALLING PREREQS ==="
# TODO: specify clangd vs ccls
sudo apt-get install ninja-build gettext cmake build-essential curl unzip ripgrep bear neofetch ccls fd-find -y

echo "=== BUILDING NEOVIM ==="
cd
git clone https://github.com/neovim/neovim.git && cd neovim
make CMAKE_BUILD_TYPE=Release
sudo make install

echo "=== INSTALLING NEOVIM CONFIG ==="
mkdir ~/.config && cd ~/.config
git clone https://github.com/kberdos/nvim.git && cd nvim
git switch container

# TODO: install neofetch and place in bashrc
# TODO: start script for podman

cd
exec bash
